services:
  - type: web
    name: nidaa-api
    runtime: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    plan: free
    region: frankfurt
    healthCheckPath: /v1/time
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: DB_SSL_NO_VERIFY
        value: "true"
      - key: MIGRATE_MODE
        value: psql
      - key: STORAGE_DRIVER
        value: local
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://nidaamasjiddjibouti.netlify.app
      - key: TRUST_PROXY
        value: "1"
